FROM	frrouting/frr

RUN		apk update && apk add iproute2 busybox

RUN		cp /etc/frr/vtysh.conf.sample /etc/frr/vtysh.conf && \
		sed -i 's/bgpd=no/bgpd=yes/g; \
				s/ospfd=no/ospfd=yes/g; \
				s/isisd=no/isisd=yes/g;' /etc/frr/deamons 
